### ISSUE TITLE
Bug reset palette couleurs + suggestions

### ISSUE THREAD

**Issue by Nicolasfr340** [diegofino15/moyennesed-v4#2]
Salut !

Petit truc à corriger, quand on reset la palette de couleur d'une matière ça la reset partout, je sais pas si c'est fait exprès mais c'est un peu embêtant quand on veut retourner à la couleur d'origine d'une matière sans tout modifier

J'ai aussi 2 suggestions concernant les couleurs:
- pouvoir choisir une couleur principale et secondaire (sinon quand on choisit du jaune ça peut mettre du fluo horrible en seconde couleur automatiquement)
- avoir une palette de couleur plus simple (en laissant quand même la possibilité d'avoir l'autre si on le souhaite) avec des couleurs prédéfinis à choisir sur une palette 10x13 ![image](https://github.com/user-attachments/assets/a83b5ef7-03be-4269-b81c-86cc2dc8159e)![image](https://github.com/user-attachments/assets/de96e440-3148-429a-86e2-624abed4af05)

**Comment by diegofino15** [comment]
Effectivement c'est bien un bug le reset des couleurs, je vais régler ça.
Pour la suggestion, ouais ça me parait pas mal du tout, tu saurais faire un prototype avec une copie du code ? (Pas grave si c'est pas le cas)

**Comment by Nicolasfr340** [comment]
Comme j'ai déjà dis, j'aimerais aider mais je ne sais pas coder :/

**Comment by diegofino15** [comment]
Le bug des couleurs est réglé, je regarde comment je pourrais implémenter la palette de couleur.
