### ISSUE TITLE
Bug accès rapide nouvelles notes

### ISSUE THREAD

**Issue by Nicolasfr340** [diegofino15/moyennesed-v4#7]
Quand on accède à une nouvelle note en accès rapide ça passe par la page de la matière au lieu que ce soit directement la note 

1. Cliquer sur la note ![image](https://github.com/user-attachments/assets/e955da9f-dc58-4cd0-9293-259013b467fc)
2. Ça affiche la page de la matière de la note pendant qlq instants ![image](https://github.com/user-attachments/assets/ecfe3701-1790-4678-bfbb-a731e05fa028)
3. Ça affiche enfin la note ![image](https://github.com/user-attachments/assets/14074fba-ea08-45a8-aeb9-9f455def9f47)

(Donc l'idée serait d'enlever l'étape intermédiaire

**Comment by diegofino15** [comment]
Réglé, la prochaine mise à jour aura ça
